name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: |
          docker build -t my-nodejs-app .

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-south-1'
        run: |
          echo "Logging in to Amazon ECR..."
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 025066249719.dkr.ecr.ap-south-1.amazonaws.com

      - name: Tag Docker image
        run: |
          docker tag my-nodejs-app:latest 025066249719.dkr.ecr.ap-south-1.amazonaws.com/node-app-js:latest

      - name: Push Docker image to ECR
        run: |
          docker push 025066249719.dkr.ecr.ap-south-1.amazonaws.com/node-app-js:latest
